server:
  port: 8081

spring:
  datasource:
    username: root
    password: asd12301230
    url: jdbc:mysql://43.143.63.236:33060/library?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
